### ISSUE TITLE
use(progress()) returns 'Undefined is not a function

### ISSUE THREAD

**Issue by kaidez** [kevva/download-status#7]
When placing the following code in index.js:

    var Download = require('download');
    var progress = require('download-status');

    var download = new Download({ strip: 1 })
       .get('myfile.txt')
       .dest('path/to/my/folder')
       .use(progress());

    download.run(function (err) {
       if (err) {
         throw err;
       }

      console.log('Download finished!');
    });

And then running `node index.js`, the following error is returned:

    /Users/me/path/to/my/repo/index.js:7
        .use(progress());
         ^
    TypeError: undefined is not a function
        at Object.<anonymous> (/Users/me/path/to/my/repo/index.js:7:6)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

Both module are in `node_modules` and I uninstalled/reinstalled them at various points. I also uninstalled/reinstalled node.

Running node v0.12.0

**Comment by kevva** [comment]
https://github.com/kevva/download/issues/45.

**Comment by kaidez** [comment]
:-)
