### ISSUE TITLE
2.2 Break on non-tty streams

### ISSUE THREAD

**Issue by coyotwill** [kevva/download-status#9]
Version 2.2 is using stream.clearLine() without checking if clearline is supported on the stream.
-> https://github.com/kevva/download-status/blob/master/index.js#L36

This breaks all non-tty outputs, including C.I. build scripts, and output redirection to files.

an example:
```
/home/XXX/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/ware/lib/index.js:21
  throw err;
        ^
TypeError: Object #<Socket> has no method 'clearLine'
    at Ware.<anonymous> (/home/XXX/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download-status/index.js:36:16)
    at Ware.<anonymous> (/home/XXX/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
    at next (/home/XXX/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/ware/lib/index.js:85:20)
    at Ware.run (/home/XXX/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/ware/lib/index.js:88:3)
    at Download.res (/home/XXX/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/index.js:199:12)
    at Request.<anonymous> (/home/XXX/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/index.js:141:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onRequestResponse (/home/XXX/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/request.js:985:10)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1658:21)
```

**Comment by nchase** [comment]
This is breaking my CI build script too.

**Comment by commandline** [comment]
```nohup npm install 1> install.log 2>&1``` will cause the failure though it doesn't capture the error above in the output. Should be useful for verifying things won't fail in CI environments.

**Comment by floatdrop** [comment]
My bad, sorry.

@kevva can you publish fix?

**Comment by kevva** [comment]
@floatdrop, published and added you to npm!
